<?php /** @var CommerceExtensions_BetterReviews_Block_Review_Helper $this */ ?>
<?php if($this->getReviewsCount()): ?>
    <?php $showStructuredData = (bool)$this->getShowStructuredData(); ?>
    <div class="ratings" <?php if($showStructuredData): ?>itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating"<?php endif; ?>>
        <?php if($this->getRatingSummary()): ?>
            <div class="rating-box">
                <div class="rating" style="width:<?php echo $this->getRatingSummary() ?>%"></div>
            </div>
        <?php endif; ?>
        <?php if($showStructuredData): ?>
            <meta itemprop="worstRating" content="1">
            <meta itemprop="ratingValue" content="<?php echo round($this->getRatingSummary() / 20, 1); ?>" />
            <meta itemprop="bestRating" content="5">
        <?php endif; ?>

        <?php if($showStructuredData): ?>
            <meta itemprop="itemReviewed" content="<?php echo $this->__($this->getProduct()->getName()); ?>" />
            <?php $reviewsCountHtml = '<span itemprop="reviewCount">' . $this->getReviewsCount() . '</span>'; ?>
            <span class="amount"><a href="<?php echo $this->getReviewsUrl() ?>"><?php echo $this->__('%s Review(s)', $reviewsCountHtml) ?></a></span>
        <?php else: ?>
            <span class="amount"><a href="<?php echo $this->getReviewsUrl(); ?>"><?php echo $this->__('%s Review(s)', $this->getReviewsCount()) ?></a></span>
        <?php endif; ?>
    </div>
<?php elseif($this->getDisplayIfEmpty()): ?>
    <p class="no-rating"><a href="<?php echo $this->getReviewsFormUrl() ?>"><?php echo $this->__('Be the first to review this product') ?></a></p>
<?php endif; ?>
